### ISSUE TITLE
which version of libquic you chose

### ISSUE THREAD

**Issue by y123456yz** [maufl/quic_toy#2]
3Q

**Comment by y123456yz** [comment]
现在官方的libquic库和你的对不上，编译不过，能否把libquic也提交到github

**Comment by y123456yz** [comment]
@quic_toy

**Comment by y123456yz** [comment]
@maufl

**Comment by y123456yz** [comment]
@maufl 
官方libquic相比以前做了很多裁剪，很多文件函数quic_toy找不到，你能否把你编译依赖的libquic源码直接上传一份

**Comment by maufl** [comment]
I'm sorry, I only speak English and German. This repository is also not maintained anymore. QUIC is quite fast moving and I would be surprised if anything in this repository still works.

**Comment by y123456yz** [comment]
@maufl
sorry,


you project depend libquic, but the libquic cut a lot of code, so quic_toy compile error.

can you send me the libquic that quic_toy depend, thanks.

my emal: 3058078489@qq.com


thanks again.

**Comment by y123456yz** [comment]
the Official libquic delete a lot of code, so quic_toy compile error.

**Comment by maufl** [comment]
I'm not sure anymore but I'll guess I was using https://github.com/devsisters/libquic/tree/694a0608ef0b1dde6eafb7c87971e08935092d92 at that point. Does this help you?

**Comment by y123456yz** [comment]
I have use the libquic that you provide, but compile error.  lots of functions can not find in libquic.
so, can you Submit your libquic code to quic_toy

**Comment by y123456yz** [comment]
@maufl
I have use the libquic that you provide, but compile error. lots of functions can not find in libquic.
so, can you Submit your libquic code to quic_toy

**Comment by y123456yz** [comment]
the Official libquic(https://github.com/devsisters/libquic/tree/694a0608ef0b1dde6eafb7c87971e08935092d92) delete a lot of code, so compile error.

**Comment by y123456yz** [comment]
can you send me the libquic that quic_toy depend.
my email: 3058078489@qq.com


thanks.

**Comment by y123456yz** [comment]
@maufl
use the libquic that you provide, compile still error.
[root@xxx quic_toy]# make
g++ --std=c++11 -fpermissive -c -g -I . -I ../libquic/src -I ../libquic/src/third_party/protobuf/src net/tools/quic/quic_client.cc -o net/tools/quic/quic_client.o
In file included from net/tools/quic/quic_client.cc:5:0:
./net/tools/quic/quic_client.h:13:29: fatal error: base/basictypes.h: No such file or directory
 #include "base/basictypes.h"
                             ^
compilation terminated.
make: *** [net/tools/quic/quic_client.o] Error 1


can you sure that you use is 694a0608ef0b1dde6eafb7c87971e08935092d92  ?
thanks

**Comment by y123456yz** [comment]
compile still error, using https://github.com/devsisters/libquic/tree/694a0608ef0b1dde6eafb7c87971e08935092d92

**Comment by maufl** [comment]
I took a look at it again, the commit 694a0608ef0b1dde6eafb7c87971e08935092d92 is the correct one. However you still need to patch libquic with the patch in this repository, I forgot to mention that in the readme.

**Comment by y123456yz** [comment]
@maufl 
I have compiled quic_toy successfully
thanks again
