### ISSUE TITLE
question about performance

### ISSUE THREAD

**Issue by huyuguang** [maufl/quic_toy#3]
I read your test result (eg: datarate-to-lost_1000Mbs.png) and found when the lost rate less or equal 1%, the TCP is much better than QUIC. And in result png about 500ms RTT, 1000Mb/s, the QUIC speed is much less than TCP.

Why? If It is because of protocol or kernel(TCP) vs application(QUIC)? Maybe because of the epoll server can not send/recv UDP packet very fast?

**Comment by y123456yz** [comment]
@huyuguang 

udp-quic have Handshake negotiation process , Encryption and decryption.
you should compare udp-quic with https(tls).

so , I think the test report is not proper.
